### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Sonkinator1991** [MadMax1960/Concursus#1]
My antivirus says that this is a trojan. I looked through the files and saw something called SOUL HACKERS2? is this safe

**Comment by MadMax1960** [comment]
The project is open source, if you feel it's not safe you can look through the code yourself. Plenty of mod tools get flagged as trojan by anti virus (r2, vortex, etc). 

Soul hackers 2 is an Atlus unity game I was testing mods with: https://store.steampowered.com/app/1777620/Soul_Hackers_2/

I thought I removed my configs for it because it can cause issues for people who don't have it, where did you see that in the files?

**Comment by Sonkinator1991** [comment]
Here:
![Screenshot 2023-10-18 015418](https://github.com/MadMax1960/Concursus/assets/137651890/e6eb49b6-3cc4-4c9d-870a-5a06687e676e)

**Comment by MadMax1960** [comment]
Ah I forgot I serialized which games were enabled/disabled. Sorry about that haha, I'll get rid of that in the next release so people don't get confused.

**Comment by jjtheboss123** [comment]
can you send me a version with it deleted? i cant make it alllowed bc chrome deletes the whole download

**Comment by MadMax1960** [comment]
Latest release doesn't have that file anymore

**Comment by Sonkinator1991** [comment]
Cool! I'll be sure to download it soon!
BTW, could you make it able to instantly find games?
________________________________
