### ISSUE TITLE
Merging issue with ply_son file (maybe)

### ISSUE THREAD

**Issue by DepHedge** [MadMax1960/Concursus#3]
Concursus Crashes when having multiple mods enabled, i press save and play and it goes halfway through then crashes

**Comment by AmberCyprian** [comment]
Here to second I'm also having the issue DepHedge is having. I also have the issue where when I go back down to only one mod, it's *still* just crashing halfway through the build process. :/

**Comment by MadMax1960** [comment]
> Here to second I'm also having the issue DepHedge is having. I also have the issue where when I go back down to only one mod, it's _still_ just crashing halfway through the build process. :/

This is really curious, just one mod shouldn't be turning merge on at all. Could you please post the file or mod that's causing this issue?

**Comment by AmberCyprian** [comment]
So I started with this mod: https://gamebanana.com/mods/474567 And it worked fine. It built and launched correctly with no issues.

I then added this mod: https://gamebanana.com/mods/474430 and the build stops partway through and crashes. I went back down to just the first mod I linked and it has continued to crash in the same manner.

Also (I can open a separate issue if you'd prefer for your own tracking) I modified the dlc_extra_pack_assets_all.bundle to be able to retexture the Rabbit models and because this bundle is in the root Sonic Superstars Directory, Concursus is having problems handling that. It will not build with my Rabbit Retexture mod at all, even when tested on a different person's system who is not having the same initial crashing issue I've been having.

Gonna try reinstalling later today to see if that fixes my first issue, but I think the DLC mod is an entirely separate issue. I've attached the DLC mod I made as it's not yet public for your own testing if you'd like in the form of a google drive link for now, since it's 44 MB.

https://drive.google.com/file/d/1hGZWMo-ToNmLOU7bLCMqNyorubSZQB55/view?usp=sharing
