### ISSUE TITLE
Help editing level files and .assets files in game that doesn't use StreamingAssets [Yooka-Laylee] 

### ISSUE THREAD

**Issue by BrochachoTheBro** [MadMax1960/Concursus#9]
I'm interested in making some texture mods for Yooka-Laylee, but it does not use the StreamingAssets .bundle file setup games like Sonic Superstars do. I know in the [Info for Mod Makers](https://github.com/MadMax1960/Concursus?tab=readme-ov-file#info-for-mod-makers) section, it says to edit the desired file in the _Data folder. However, when I went to find the Animator folder where Yooka and Laylee's models are located (Model YookaLaylee, Model YookaLaylee_Cutscene, YookaLaylee_combined) I noticed an insane amount of repeats of these models in a majority of the level files. I also couldn't find these models in any of the sharedassets files, which is leaving me pretty confused. Would I seriously have to replace every single instance of the assets I want to use my custom textures in every single level file they appear in? Or is there another I'm supposed to go about this.

**Comment by MadMax1960** [comment]
So unless I'm mistaken you essentially have a bunch of repeated files in various asset bundles? If so then yeah manually replacing each one, or making a bepinex/melonloader mod to make the game only use one of those uassets instead of the duplicates woul be what you need to do yeah. Unfortunately this is a game specific issue in some games and not something I can really account for in Concursus as there's not some universal unity api I can use to resolve stuff like this.

**Comment by MadMax1960** [comment]
Though if you do make a bepinex or melonloader, plugin, this is also supported to include in your mod 🙂. Info about that is a little lower in the info for mod makers section you were looking at.

**Comment by BrochachoTheBro** [comment]
> Though if you do make a bepinex or melonloader, plugin, this is also supported to include in your mod 🙂. Info about that is a little lower in the info for mod makers section you were looking at.

uhh i wouldnt say im a programmer at all so i dont think thats a possibility for me, and considering there is basically no modding scene for this game, im kinda out of luck...
